### ISSUE TITLE
Define the log folder

### ISSUE THREAD

**Issue by ThaDafinser** [piersharding/php-sapnwrfc#10]
If u have tracing enabled or there are errors, sapnwrfc create log `*.trc` file in the current directory.

Can u somehow define that directory?

**Comment by piersharding** [comment]
Hi -

I don't think there is any control over this - http://help.sap.com/saphelp_nwpi711/helpdata/en/48/c7bb09da5e31ebe10000000a42189b/content.htm

You could try changing the current working directory ?

**Comment by ThaDafinser** [comment]
Changing the cwd works. I added it in the documentation as a hint: https://github.com/piersharding/php-sapnwrfc/pull/11/files
