### ISSUE TITLE
httpd processes appear to hang when restarting gracefully if sapnwrfc is loaded

### ISSUE THREAD

**Issue by ct16k** [piersharding/php-sapnwrfc#13]
Hello,

I'm facing a weird issue with this module on a CentOS 6 up-to-date.

If the sapnwrfc module is loaded, whenever I issue a `service httpd graceful` command, all the current httpd workers will remain in a "closing connection" or "gracefully finishing" state, e.g.
```
Srv	PID	Acc	M	CPU 	SS	Req	Conn	Child	Slot	Client	VHost	Request
0-0	21077	53/255/255	C 	0.13	33	0	208.3	0.86	0.86 	172.31.16.254	127.0.0.1:80	GET /server-status HTTP/1.1
1-0	21078	0/202/202	G 	0.11	304	0	0.0	0.73	0.73 	172.31.16.254	127.0.0.1:80	GET /server-status HTTP/1.1
2-0	21079	0/202/202	G 	0.10	518	0	0.0	0.68	0.68 	172.31.16.254	127.0.0.1:80	GET /server-status HTTP/1.1
3-0	21080	0/202/202	G 	0.10	197	0	0.0	0.75	0.75 	172.31.16.254	127.0.0.1:80	GET /server-status HTTP/1.1
4-0	21081	0/202/202	G 	0.10	411	0	0.0	0.76	0.76 	172.31.16.254	127.0.0.1:80	GET /server-status HTTP/1.1
5-0	21082	0/202/202	G 	0.11	90	0	0.0	0.77	0.77 	172.31.16.254	127.0.0.1:80	GET /server-status HTTP/1.1
```

If multiple graceful restarts are performed, all worker slots eventually fill up and httpd starts replying with a 503 code. The interesting fact here is that the httpd processes themselves actually end execution (i.e. PIDs 21077-21082 no longer exist). If I do a reload/restart, the workers list is cleared up.

If I comment out loading the sapnwrfc.so extension, everything behaves properly again.

I've tried this against various versions of httpd, apr and php, from the CentOS provided ones (httpd 2.2.15 and php 5.3.3) to the latest available (httpd 2.4.16, apr 1.5.2 and php 5.6.12), and every time I get the same thing.

Another weird behaviour is that setting a breakpoint inside the module shutdown function and doing a step-by-step execution until the child process exits causes the worker slot to be properly cleared. This is actually why I started checking against other versions as well, thinking it may be a bug in apr that causes some events, like the shutdown finishing up, to be missed. And I'm still not sure this isn't a bug in something else, not sapnwrfc, but so far it's the only constant in all the tests I've done (except the underlying OS).

I tried looking at the source code for anything obvious, but unfortunately have no experience writing PHP modules, so came up empty. But I'm more than willing to help troubleshoot and fix this, so any pointers on how to go about it are more than welcome.

Thank you!

**Comment by piersharding** [comment]
Hi -

I'm wondering if this is a threading issue - are you using mpm worker?  I would try using prefork mode for Apache and see if that changes things.

Cheers,
Piers Harding.

**Comment by ct16k** [comment]
I'm already using 'prefork', since php compilation throws an error if something else is specified.

**Comment by ct16k** [comment]
This turned out to be a NW RFC issue. Updating the SDK to the latest version available and rebuilding the module made the issue go away.

Apologies for the noise and thank you for the help!
