### ISSUE TITLE
Works for PHP7

### ISSUE THREAD

**Issue by ThaDafinser** [piersharding/php-sapnwrfc#15]
Hello @piersharding ,

did you already tried your extension with PHP7?

If it works for *nix i will try to build a Windows extension again, but since my lack of C skills i better wait until it works for *nix

**Comment by piersharding** [comment]
Hi - no, I haven't tried it for PHP7.

**Comment by ThaDafinser** [comment]
Thx for the quick response.

When anybody tried it successfully, i will try to build them for windows :+1:

**Comment by themasch** [comment]
Just tried it. Compiles fine, but when loading it failes with ` /usr/lib64/php/modules/sapnwrfc.so: undefined symbol: zval_used_for_init`

**Comment by ThaDafinser** [comment]
There is a upgrade guide https://wiki.php.net/phpng-upgrading

**Comment by ThaDafinser** [comment]
@themasch or @piersharding is someone of you working or will work next time on porting it to PHP7?
For me it's currently the only missing extension to switch to PHP7.

If none of you is working on it, i may try it, but i don't know if i really can accomplish it with my lack of knowledge here.

**Comment by themasch** [comment]
We started using json-rpc instead of rfc so we don't depend on this extensions. So I'm not working on this and probably wont in the near future

**Comment by gkralik** [comment]
I plan to have a look at it during the christmas holidays. My C skills are limited, though...

**Comment by ThaDafinser** [comment]
I have a "work in progress" branch here https://github.com/ThaDafinser/php-sapnwrfc/tree/feature/php7

- updated all README + INSTALL
- rewritten online + offline tests for `phpunit`
- cleared files out of the root (some moved to bin/, some deleted)
- updated license headers

**Comment by ThaDafinser** [comment]
@gkralik i couldnt complete the PHP7 port until yet. It's really hard without good C knowledge

The upgrade guide is only one part. There are some other parts, which have no documentation in the guide :-1:

**Comment by gkralik** [comment]
I'm working on it, but it'll take some time as my C skills are limited. I managed to figure out a few of the not so well documented parts...

**Comment by ThaDafinser** [comment]
Cool thing. I moved my general cleanup work to this PR (without touching C or H files)
 https://github.com/piersharding/php-sapnwrfc/pull/17

**Comment by gkralik** [comment]
I finally got some time and started working on a SAP NW RFC extension for PHP7. It is very much a work in progress, but we'll get there: [gkralik/php7-sapnwrfc](https://github.com/gkralik/php7-sapnwrfc)

**Comment by gkralik** [comment]
The PHP7 extension ([gkralik/php7-sapnwrfc](https://github.com/gkralik/php7-sapnwrfc)) is now in a beta state and should be usable. The API changed a little bit, but it should not be hard to get started.

Testers welcome.

**Comment by manudum** [comment]
@gkralik thanks for this work
Compilation Ok on Linux
But I have a segmentation fault when trying to call BAPI_PO_CREATE

Call BAPI_PO_CREATE1
array(8) [
    'POHEADER' => array(7) [
        'DOC_DATE' => string (8) "20160218"
        'DOC_TYPE' => string (4) "ZPEP"
        'PURCH_ORG' => string (4) "ARED"
        'PUR_GROUP' => string (3) "PEP"
        'VENDOR' => string (10) "0010113261"
        'COMP_CODE' => string (4) "1862"
        'ITEM_INTVL' => string (0) ""
    ]
    'POHEADERX' => array(8) [
        'DOC_DATE' => string (1) "X"
        'DOC_TYPE' => string (1) "X"
        'PURCH_ORG' => string (1) "X"
        'PUR_GROUP' => string (1) "X"
        'VENDOR' => string (1) "X"
        'CREATED_BY' => string (1) "X"
        'COMP_CODE' => string (1) "X"
        'ITEM_INTVL' => string (1) "X"
    ]
    'POITEM' => array(1) [
        array(15) [
            'PO_ITEM' => string (5) "00100"
            'DELETE_IND' => string (1) " "
            'MATL_GROUP' => string (9) "PRES_PEPI"
            'STGE_LOC' => string (4) "PEP1"
            'SHORT_TEXT' => string (40) "1-duo femme jeune et femme senior - 1450"
            'PLANT' => string (4) "0110"
            'VEND_MAT' => string (6) "CM 420"
            'PO_UNIT_ISO' => string (3) "PRE"
            'NET_PRICE' => string (5) "1.000"
            'QUANTITY' => string (6) "183.00"
            'PO_PRICE' => string (1) "2"
            'TRACKINGNO' => string (7) "1813426"
            'RET_ITEM' => string (0) ""
            'ACCTASSCAT' => string (0) ""
            'MATERIAL' => string (18) "000000000009001740"
        ]
    ]
    'POITEMX' => array(1) [
        array(16) [
            'PO_ITEM' => string (5) "00100"
            'PO_ITEMX' => string (1) "X"
            'DELETE_IND' => string (1) "X"
            'MATL_GROUP' => string (1) "X"
            'STGE_LOC' => string (1) "X"
            'SHORT_TEXT' => string (1) "X"
            'PLANT' => string (1) "X"
            'VEND_MAT' => string (1) "X"
            'QUANTITY' => string (1) "X"
            'PO_UNIT_ISO' => string (1) "X"
            'NET_PRICE' => string (1) "X"
            'PO_PRICE' => string (1) "X"
            'TRACKINGNO' => string (1) "X"
            'ACCTASSCAT' => string (1) "X"
            'RET_ITEM' => string (1) "X"
            'MATERIAL' => string (1) "X"
        ]
    ]
    'POACCOUNT' => array()
    'POACCOUNTX' => array()
    'POSCHEDULE' => array(1) [
        array(2) [
            'PO_ITEM' => string (5) "00100"
            'DELIVERY_DATE' => string (8) "20160202"
        ]
    ]
    'POSCHEDULEX' => array(1) [
        array(3) [
            'PO_ITEM' => string (5) "00100"
            'PO_ITEMX' => string (1) "X"
            'DELIVERY_DATE' => string (1) "X"
        ]
    ]
]
==> error_log <==
[Thu Feb 18 15:38:17.791495 2016] [core:notice] [pid 1185:tid 140262994323264] AH00052: child pid 5992 exit signal Segmentation fault (11)

**Comment by gkralik** [comment]
Please open a separate issue if you're having trouble with the PHP7 version at [gkralik/php7-sapnwrfc](https://github.com/gkralik/php7-sapnwrfc).
