### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'sapnwrfc' not found

### ISSUE THREAD

**Issue by reiluke** [piersharding/php-sapnwrfc#21]
Hi Piersharding,

The extension is loaded in php/apache, but when i try a sample it returns
PHP Fatal error:  Uncaught Error: Class 'sapnwrfc' not found

Were using saprfc for php5.4 and were thingking of upgrading

thanks

**Comment by reiluke** [comment]
This line works

if (! extension_loaded('sapnwrfc')) {
    echo ('Extension "sapnwrfc" not loaded. Please see https://github.com/piersharding/php-sapnwrfc#installation');
}
the error is triggered with the instantiate 

$conn = new sapnwrfc($config);

**Comment by piersharding** [comment]
Hi -

You may want to have a look at this version - https://github.com/gkralik/php7-sapnwrfc

Cheers,
Piers

**Comment by reiluke** [comment]
thanks will try, i wish you would put up release builds in 32bit, most php/apache production is in 32bit because its more stable

**Comment by piersharding** [comment]
Do you mean most windows versions are 32bit?  If that is the case then I don't do windows and leave that up to others.  More importantly, the RFC SDK supplied by SAP is proprietary so I have no intention of distributing it.
If you have legal access to SAP then you should have legal access to the SDK and then building the library should be reasonably straight forward.
