### ISSUE TITLE
Windows build: my current result

### ISSUE THREAD

**Issue by ThaDafinser** [piersharding/php-sapnwrfc#6]
I'm currently trying to build this as a windows extension.

My dev enviroment on the php side should be fine ... already compiled some other php-extensions. But it seems i have at least one error left with this extension.

My progress so far:

## building as dll with VS2012
I "sucessfully" created the dll with VS2012 for TS and NTS. (the build log says that...)
https://gist.github.com/ThaDafinser/e6380157c4f77a3286e5#file-log_nts-txt
https://gist.github.com/ThaDafinser/e6380157c4f77a3286e5#file-log_ts-txt

But when loading this extension with php it complains:
`PHP Startup: Invalid library (maybe not a PHP library) 'php_sapnwrfc.dll' in Unknown on line 0`

## building with config.w32 (counter file of config.m4)
So i tried another approach: Building a `config.w32` file.
https://gist.github.com/ThaDafinser/e6380157c4f77a3286e5#file-config-w32
Note: i moved the SAP NW RFC files inside the extension folder `nwrfcsdk/[lib]|[include]`
The files are already checked in the `config.w32` files and when extecutiong `configure --options....` all seems to be fine
https://gist.github.com/ThaDafinser/e6380157c4f77a3286e5#file-configure-log

command `nmake` doesnt complain...

when executing `nmake snap` it complains:
```cli
WARNING: distro depends on msvcr110.dll, but could not find it on your system
WARNING: distro depends on sapnwrfc.dll, but could not find it on your system
```
https://gist.github.com/ThaDafinser/e6380157c4f77a3286e5#file-gistfile1-txt

When i run `sample.php` i already come to this output(without dl function at begin):
```cli
sapnwrfc version: 0.11
nw rfc sdk version: major: 7200 minor: 0 patch: 22
```

Then at the line `$conn = new sapnwrfc($config);` is breaks:
```cli
Run-Time Check Failure #2 - Stack around the variable 'errorInfo' was corrupted
```

## Notes / Questions
- My resources: 
  - https://wiki.php.net/internals/windows/stepbystepbuild     
  - http://www.php.net/manual/en/internals2.buildsys.configwin.php 
  - http://www.dreamincode.net/forums/topic/244215-introduction-to-creating-a-php-extension-for-windows/
- on this download site there are some old windows builds (which were my base partly), but i can't find the author of them 
  - http://www.piersharding.com/download/php/sapnwrfc/
- i enabled the debug mode now...
- any other idea?

**Comment by ThaDafinser** [comment]
I started off fresh with following steps:
1) Follow the dev setup https://wiki.php.net/internals/windows/stepbystepbuild
2) Copy from nwrfcsdk (7200.613.22.50635) the include + lib to C:\php-sdk\phpdev\vc11\x86\deps\[include|lib] (32bit)...since PHP is build x86
3) copy msvcr110.dll to C:\php-sdk\phpdev\vc11\x86\deps\lib (was missing and is needed for php.exe as well)
3) use this custom created config.w32
```
// $Id$
// vim:ft=javascript

ARG_WITH("sapnwrfc", "*****SAP NW RFC*****", "no");
if (PHP_SAPNWRFC != "no") {
	
	//checking for header
	sap_nw_rfc_header = CHECK_HEADER_ADD_INCLUDE("sapnwrfc.h", "CFLAGS_SAPNWRFC");
	if (sap_nw_rfc_header) {
	} else{
		WARNING("sapnwrfc not enabled; header sapnwrfc.h not found");
	}
	
	//checking for library
	sap_nw_rfc_lib = CHECK_LIB("sapnwrfc.lib", "sapnwrfc", PHP_SAPNWRFC);
	if (sap_nw_rfc_header && sap_nw_rfc_lib) {
	 	EXTENSION("sapnwrfc", "sapnwrfc.c");
	} else{
		WARNING("sapnwrfc not enabled; lib sapnwrfc.lib not found");
	}
}
```
4) Execute
```
configure --disable-all --enable-cli --with-sapnwrfc=shared --disable-zts
```
5) include the `php_sapnwrfc.dll`
6) phpInfo shows (only table header)
```
sapnwrfc
sapnwrfc support	enabled
```
7) When using a saprfc function this error comes up: `saprfc extension is not installed. Please install/configure it: http://sourceforge.net/projects/saprfcsdk/`

8) Since the log doesnt give me anything useful, maybe you got a last idea?
-> See log: https://gist.github.com/ThaDafinser/ca3d237a17a71bfa4c8a


If we get this finally running, i would also like to get this on pecl.php.net that the builds for windows are done automatically, if you are fine with it @weltling

//cc @piersharding

**Comment by piersharding** [comment]
Hi -
I'm not sure why you are referring to saprfc (by Eduard) as that is a different implementation to sapnwrfc.  I'm fairly sure that you will have problems trying to get x86 working as the SAP NW RFC SDK is 64bit only?  So first of all make sure that you are not using saprfc (remove all traces of it from your build and php config), and make sure that you are using the MS Visual C++ compiler.  
I do not have a Windows development environment so I can't build this for you.  From time to time someone from the mailing lists will do one for me and I make it available for download.

Cheers,
Piers Harding.

**Comment by weltling** [comment]
@ThaDafinser for your previous error logs - you was linking x86 PHP to a x64 SAP library. That won't work, probably was the reason for those "undefined symbol" errors. It doesn't really matter what the platform is, but merely that you link correct libs together. Be sure you're on the right env, you can check it with like "cl /?".

Another point - one shouldn't copy the CRT DLL, instead it's enough to install a VS2012 redistributable on the target machine (with VS it's present automatically). So merely what is needed for the php_*.dll is the CRT, the PHP DLL, if it's linked against some dependency DLL -that too, on the path. For production, you can copy sapnwrfc.dll into PHP dir, otherwise just prepend %path% with the correct location.

With PECL - while the sapnwrfc ext itself is under PHP how it looks, there might be a legal issue with linking against (and/or redistributing) the dependency binaries. For instance, i was about to give it a quick try, but wasn't able to obtain the dependency SDK.

**Comment by chemik3** [comment]
Hi,
you can download compiled php module for saprfc and sapnwrfc projects here: https://sourceforge.net/projects/saprfcsapnwrfc/files/?source=navbar

**Comment by piersharding** [comment]
Hi - Thanks for providing the compiled binaries.  I'll point to this in the README.
Cheers,
Piers Harding.

**Comment by ThaDafinser** [comment]
@chemik3 AWESOME! But it's only for the x64 build and not for the x86?

**Comment by chemik3** [comment]
I like to compile for x86 architecture but i can't find SAP NW RFC SDK or SAP RFC SDK for x86(windows) on SAP Marketplace. If you have that version of SDK can you send me?

**Comment by ThaDafinser** [comment]
@chemik3 i think i have the correct ones, where can i send you the files?

**Comment by ThaDafinser** [comment]
@chemik3 maybe you also want to share the build configuration, that we maybe can provide the `config.w32` file`?

**Comment by chemik3** [comment]
I was used following preprocessor directives:

WIN32
_WINDOWS
_USRDLL
SAPNWRFC_EXPORTS
ZEND_WIN32
PHP_WIN32
ZTS=1
ZEND_DEBUG=0
COMPILE_DL_SAPNWRFC
_UNICODE
UNICODE
SAPwithUNICODE

**Comment by chemik3** [comment]
I was used following preprocessor directives:

WIN32
_WINDOWS
_USRDLL
SAPNWRFC_EXPORTS
ZEND_WIN32
PHP_WIN32
ZTS=1
ZEND_DEBUG=0
COMPILE_DL_SAPNWRFC
_UNICODE
UNICODE
SAPwithUNICODE

**Comment by chemik3** [comment]
You can send SAP NW RFC SDK here: novak at sapnet.cz

**Comment by ThaDafinser** [comment]
Thank you @chemik3 for the directives!

**Comment by inceddy** [comment]
Did you make any progress regarding the SAPRFC extension?
I have no clue about compiling PHP and C/C++. But this is what I tryed:

config.w32 
````
// $Id$
// vim:ft=javascript

ARG_WITH("saprfc", "Support of SAPRFC", "no");

if (PHP_SAPRFC != "no") {
    EXTENSION("saprfc", "saprfc.c rfccal.c", false);
    ADD_SOURCES("ext/saprfc/rfcsdk/include", "sapirfci.c");

    ADD_FLAG("CFLAGS_SAPRFC","/D WIN32 /D SAPRFC_EXPORTS /D COMPILE_DL_SAPRFC /D ZEND_DEBUG=0 /D NDEBUG /D _WINDOWS /D _USRDLL /D ZEND_WIN32 /D PHP_WIN32 /D _USE_32BIT_TIME_T /D ZTS=1");

    PHP_INSTALL_HEADERS("ext/saprfc", "php_saprfc.h rfccal.h");
    PHP_INSTALL_HEADERS("ext/saprfc/rfcsdk/include", "rfcpump.h rfcsi.h sapconn.h sapirfc.h sapitab.h sapmtx.h sapobj.h saprfc.h sapuc.h sapucx.h srfcserv.h srfctest.h trfcserv.h trfctest.h")

}
````
I'm using the rfcsdk 6.20 located in the extension folder.
Also I changed the saprfc.h due to errors I got. All `RETURN_RESOURCE(zend_list_insert(rfc_resource, le_rfc));` need an `TSRMLS_CC` after the second argument and `function_entry` becomes `zend_function_entry`.

Now I get linker errors I can not solve. 
````
Microsoft (R) Program Maintenance Utility, Version 11.00.50727.1
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Recreating build dirs
sapirfci.c
   Bibliothek "Release_TS\php5ts.lib" und Objekt "Release_TS\php5ts.exp" werden
erstellt.
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcL
astError@4" in Funktion "___cal_last_error".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcO
penEx@8" in Funktion "__cal_open".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcI
nstallStructure@16" in Funktion "___cal_table".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcC
allReceive@24" in Funktion "___cal_fce_call".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcI
ndirectCallEx@20" in Funktion "___cal_fce_indirect_call".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcG
etData@12" in Funktion "___sal_get_data".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcS
endData@12" in Funktion "___sal_send_data".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcR
aise@8" in Funktion "___sal_raise".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcR
aiseTables@12" in Funktion "___sal_raise".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcC
onfirmTransID@8" in Funktion "___cal_fce_indirect_call".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcG
etAllLibVersions@8" in Funktion "___cal_lib_version".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcC
onvertCharToBcd@20" in Funktion "_cal_conv_string_to_rfc".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcC
onvertBcdToChar@20" in Funktion "_cal_conv_rfc_to_string".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_ItCr
eate@16" in Funktion "___cal_table".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_ItDe
lete@4" in Funktion "___cal_del_fce".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_ItGe
tLine@8" in Funktion "___cal_table".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_ItPu
tLine@12" in Funktion "___cal_table".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_ItIn
sLine@8" in Funktion "___cal_table".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_ItAp
pLine@4" in Funktion "___cal_table".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_ItDe
lLine@8" in Funktion "___cal_table".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_ItFr
ee@4" in Funktion "___cal_table".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_ItFi
ll@4" in Funktion "___cal_table".
rfccal.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_ItLe
ng@4" in Funktion "___cal_table".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcA
ccept@4" in Funktion "__zval_copy_ctor".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcA
cceptExt@4" in Funktion "__zval_copy_ctor".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcC
lose@4" in Funktion "__free_resource_rfc".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcA
bort@8" in Funktion "__zval_copy_ctor".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcS
etCodePage@8" in Funktion "__zval_copy_ctor".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcG
etAttributes@8" in Funktion "__zval_copy_ctor".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcC
heckRegisterServer@32" in Funktion "__zval_copy_ctor".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcC
ancelRegisterServer@24" in Funktion "__zval_copy_ctor".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcG
etNameEx@8" in Funktion "__zval_copy_ctor".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcW
aitForRequest@8" in Funktion "__zval_copy_ctor".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcI
nstallFunction@12" in Funktion "__zval_copy_ctor".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcI
nstallTransactionControl@16" in Funktion "__zval_copy_ctor".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcC
reateTransID@8" in Funktion "__zval_copy_ctor".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcA
llowStartProgram@4" in Funktion "__zval_copy_ctor".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcS
etTrace@8" in Funktion "__zval_copy_ctor".
saprfc.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "_RfcG
etTicket@8" in Funktion "__zval_copy_ctor".
Release_TS\php5ts.dll : fatal error LNK1120: 39 nicht aufgelöste Externe
NMAKE : fatal error U1077: ""C:\Program Files (x86)\Microsoft Visual Studio 11.0
\VC\BIN\cl.exe"": Rückgabe-Code "0x2"
Stop.
```` 

Any ideas about that?

**Comment by chemik3** [comment]
inceddy: The easiest way to get precompiled binaries is download it here:
  
https://sourceforge.net/projects/saprfcsapnwrfc/files/?source=navbar

**Comment by inceddy** [comment]
The problem is, thar I need this extension for at least 3 different PHP versions and in 32bit :/

**Comment by chemik3** [comment]
For which version of PHP you need extension?

novak (at) sapnet.cz

**Comment by inceddy** [comment]
5.6.3, 5.5.11, 5.4.19 all in x86 architecture.

**Comment by chemik3** [comment]
I tested now that version bellow supported also PHP 5.6.3

https://sourceforge.net/projects/saprfcsapnwrfc/files/?source=navbar

i will try to compile also for previous version of PHP.

**Comment by inceddy** [comment]
Not for me due to x64 architecture.

**Comment by chemik3** [comment]
It is supporting both x86 and x64 architecture:

![image](https://cloud.githubusercontent.com/assets/6068079/7156280/93841ae4-e365-11e4-9207-9b966c59fcb2.png)

**Comment by inceddy** [comment]
Maybe I'm in the wrong thread. I'm looking for SAPRFC not SAPNWRFC (btw. I don't know the difference). Got here from a comment on http://stackoverflow.com/questions/28170742/how-to-install-saprfc-with-php-5-4-4-in-windows-32-system

**Comment by chemik3** [comment]
SAPRFC ans SAPNWRFC are different projects. I like to compile SAPRFC binaries for x86 but sap probably not supported x86 on windows and I can't download SAP RFC SDK for this architecture:
![image](https://cloud.githubusercontent.com/assets/6068079/7156622/42a0e35c-e368-11e4-899d-218b918ff98a.png)

If you have x86 version of SDK send me and i will try compile php extension.

**Comment by inceddy** [comment]
I could send you the sdk version 6.2 x86.

**Comment by ThaDafinser** [comment]
@inceddy sorry for the comment on stackoverflow...yes sapnwrfc != saprfc

I create a guide here how i finally could compile it with Visual Studio.
https://github.com/piersharding/php-sapnwrfc/tree/master/builds

I failed while creating the `config.w32` file, but i see you made there some progress with the flags :+1: 

@chemik3 will be the right guy here to help, since he seems to know what he does here and does not try + error like me xD

**Comment by inceddy** [comment]
Somewhere I read, that one can use the Windows Server on IA32 32bit SDK for compiling on windows x86. Maybe you could give this a try.

**Comment by chemik3** [comment]
I doubt that.

**Comment by inceddy** [comment]
This was mentioned on http://sourceforge.net/p/saprfcsdk/wiki/SAPRfcSdk%20-%20Axel%20Arnold%20Bangert%20-%20Herzogenrath%202013/
> You have to use the IA x32 Version for example (SAP RFC SDK 7.20 for Windows Server on IA32 32bit) librfc32.dll for Win32 from RFCSDK (it is part of SAPGUI for Windows too, which is under the License of SAP)

**Comment by chemik3** [comment]
I compiled SAPRFC for x86 for PHP 5.6, you can download here:

https://sourceforge.net/projects/saprfcsapnwrfc/files/saprfc-1.4.1.zip/download

check if that works.

**Comment by inceddy** [comment]
Allmost. I get the following error on starting up the apache.
````
PHP Startup: saprfc: Unable to initialize module
Module compiled with module API=20131226
PHP    compiled with module API=20121212
````
It would be awsome if you could share the information how you made this work ;)

**Comment by inceddy** [comment]
Awsome! It works!
It would be nice if you could share the information how you made this work ;) Than I would give a try to compile it for 5.4 and 5.5 myself.

How ever @chemik3 thank you very much!

**Comment by chemik3** [comment]
I was compiled saprfc also for PHP 5.5/x86 and updated files here:

https://sourceforge.net/projects/saprfcsapnwrfc/files/?source=navbar

**Comment by waldmeisterx** [comment]
I'm looking for a SAPRFC x86 for PHP 5.6 but **NTS** version.
The versions given above are all **TS** (threadsafe).

**@chemik3** could you compile such a version as well?
(I think, remove the prepocessor parameter ZTS=1 will do it?)

**Comment by chemik3** [comment]
waldmeisterx: Try following file and let me know if works:

http://monka.hysteria.cz/~chemik/sap/php_saprfc_PHP5.6_x86_nts.dll

**Comment by waldmeisterx** [comment]
@chemik3: Thank a lot for the quick response! :)
First quick test ist positive! PHP loads the extension without error and it shows up in phpinfo().
Quick funcional check ist positive too, but let me do some more functional checks today.

**Comment by ThaDafinser** [comment]
@chemik3 @waldmeisterx there are also some here: https://github.com/piersharding/php-sapnwrfc/tree/master/builds

**Comment by waldmeisterx** [comment]
@ThaDafinser yes, but these are sap**nw**rfc an these differ from (old) saprfc!

**Comment by waldmeisterx** [comment]
@chemik3: Now I have finished some more and detailed tests. It works like a charm. :)
Thank you very much for the very fast support! 
Now I can prepare the PHP upgrade, for which I need the new dll.

**Comment by jazzhh** [comment]
Hi, is there anybody who is able to create a sap**nw**rfc.dll für PHP Version 5.2.14 x86? Thans in advance :)

**Comment by ThaDafinser** [comment]
@jazzhh 5.2 is not supported anymore. Please upgrade

**Comment by jazzhh** [comment]
@ThaDafinser OK, which version do you recommend?

**Comment by ThaDafinser** [comment]
@jazzhh of course PHP7 if you can upgrade already
Otherwise you should upgrade to PHP 5.5 at least (which have at least security support until 31 Dec 2018)

http://php.net/supported-versions.php
http://php.net/eol.php

**Comment by jazzhh** [comment]
@ThaDafinser Allright, thank you!
